
package bloconotasswing;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author thoma
 */
public class blocodenotas extends javax.swing.JFrame {

    /**
     * Creates new form blocodenotas
     */
    public blocodenotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextPane();
        seletor = new javax.swing.JFileChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnArquivo = new javax.swing.JMenu();
        btnNovo = new javax.swing.JCheckBoxMenuItem();
        btnAbrir = new javax.swing.JCheckBoxMenuItem();
        btnSalvar = new javax.swing.JCheckBoxMenuItem();
        mnEditar = new javax.swing.JMenu();
        btnColar = new javax.swing.JCheckBoxMenuItem();
        btnRecortar = new javax.swing.JCheckBoxMenuItem();
        btnCopiar = new javax.swing.JCheckBoxMenuItem();
        mnAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(txtResultado);

        mnArquivo.setText("Arquivo");

        btnNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnNovo.setSelected(true);
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        mnArquivo.add(btnNovo);

        btnAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnAbrir.setSelected(true);
        btnAbrir.setText("Abrir");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        mnArquivo.add(btnAbrir);

        btnSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnSalvar.setSelected(true);
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        mnArquivo.add(btnSalvar);

        jMenuBar1.add(mnArquivo);

        mnEditar.setText("Editar");

        btnColar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnColar.setSelected(true);
        btnColar.setText("Colar");
        btnColar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbtnColarActionPerformed(evt);
            }
        });
        mnEditar.add(btnColar);

        btnRecortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnRecortar.setSelected(true);
        btnRecortar.setText("Recortar");
        btnRecortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecortarActionPerformed(evt);
            }
        });
        mnEditar.add(btnRecortar);

        btnCopiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnCopiar.setSelected(true);
        btnCopiar.setText("Copiar");
        btnCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarActionPerformed(evt);
            }
        });
        mnEditar.add(btnCopiar);

        jMenuBar1.add(mnEditar);

        mnAjuda.setText("Ajuda");
        jMenuBar1.add(mnAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(seletor, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seletor, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbtnColarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbtnColarActionPerformed
        txtResultado.paste();
    }//GEN-LAST:event_btnbtnColarActionPerformed

    private void btnRecortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecortarActionPerformed
        txtResultado.cut();
    }//GEN-LAST:event_btnRecortarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        txtResultado.setText("");
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarActionPerformed
        txtResultado.copy();
    }//GEN-LAST:event_btnCopiarActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        int abrir = seletor.showOpenDialog(this);
        if(abrir == JFileChooser.APPROVE_OPTION){
           File arquivo = seletor.getSelectedFile();
           try{
            BufferedReader ler = new BufferedReader(new FileReader(arquivo));
            String conteudo = "";
            String ver = "";
            while(ver!= null){
                ver = ler.readLine();
                if(ver!= null){
                    conteudo += ver+"\n";
                }
            }
            txtResultado.setText(conteudo);
           }
           catch(Exception erro){
               JOptionPane.showMessageDialog(this,"O arquivo não pode ser carregado","",JOptionPane.ERROR_MESSAGE);
           }
        }
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        int salvar = seletor.showSaveDialog(this);
            if(salvar == JFileChooser.APPROVE_OPTION){
            File arquivo = seletor.getSelectedFile();
            String conteudo = txtResultado.getText();
            try{
                FileWriter writer = new FileWriter(arquivo);
                BufferedWriter buffer = new BufferedWriter(writer);
                buffer.write(conteudo);  
                buffer.close();
               
            }
            catch(Exception erro){
                JOptionPane.showMessageDialog(this,"O arquivo já existe","Erro!",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(blocodenotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(blocodenotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(blocodenotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(blocodenotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new blocodenotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem btnAbrir;
    private javax.swing.JCheckBoxMenuItem btnColar;
    private javax.swing.JCheckBoxMenuItem btnCopiar;
    private javax.swing.JCheckBoxMenuItem btnNovo;
    private javax.swing.JCheckBoxMenuItem btnRecortar;
    private javax.swing.JCheckBoxMenuItem btnSalvar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mnAjuda;
    private javax.swing.JMenu mnArquivo;
    private javax.swing.JMenu mnEditar;
    private javax.swing.JFileChooser seletor;
    private javax.swing.JTextPane txtResultado;
    // End of variables declaration//GEN-END:variables
}
